const sampledata = [{
        id: 1,
        "name": "Etios",
        "brand": "Toyota",
        "model": "Sedan",
        "fuel": "Diesel",
        "mileage": 15,
        "wheels": 4,
        "seater": 5,
        "price": 2500,
        "img": "https://www.bookyourcar.co.in/uploads/colorimage/10645_Toyota%20Etios%20Liva%20silver.jpg",
        "isAvailable": true
    },
    {
        id: 2,
        "name": "Swift Dzire",
        "brand": "Maruti Suzuki",
        "model": "Sedan",
        "fuel": "Diesel",
        "mileage": 13,
        "wheels": 4,
        "seater": 6,
        "price": 2000,
        "img": "https://img.gaadicdn.com/images/carexteriorimages/630x420/Maruti/Maruti-Swift-Dzire-2011-2014/3840/1561977133129/front-left-side-47.jpg",
        "isAvailable": true
    },
    {
        id: 3,
        "name": "Innova",
        "brand": "Toyota",
        "model": "SUV",
        "fuel": "Diesel",
        "mileage": 16,
        "wheels": 4,
        "seater": 5,
        "price": 2500,
        "img": "https://4.imimg.com/data4/SN/PL/MY-10330151/toyota-innova-with-a-c-5-1-500x500.jpg",
        "isAvailable": true
    },
    {
        id: 4,
        "name": "Duster",
        "brand": "Renault",
        "model": "SUV",
        "fuel": "Petrol",
        "wheels": 4,
        "mileage": 12,
        "seater": 5,
        "price": 3000,
        "img": "https://images.jdmagicbox.com/quickquotes/images_main/renault_duster_85ps_diesel_rxe_pearl_supreme_white_82809470_0.jpg",
        "isAvailable": true
    }, {
        id: 5,
        "name": "Etios",
        "brand": "Toyota",
        "model": "Sedan",
        "fuel": "Diesel",
        "mileage": 15,
        "wheels": 4,
        "seater": 5,
        "price": 2500,
        "img": "https://www.bookyourcar.co.in/uploads/colorimage/10645_Toyota%20Etios%20Liva%20silver.jpg",
        "isAvailable": true
    },
    {
        id: 6,
        "name": "Swift Dzire",
        "brand": "Maruti Suzuki",
        "model": "Sedan",
        "fuel": "Diesel",
        "mileage": 13,
        "wheels": 4,
        "seater": 6,
        "price": 2000,
        "img": "https://img.gaadicdn.com/images/carexteriorimages/630x420/Maruti/Maruti-Swift-Dzire-2011-2014/3840/1561977133129/front-left-side-47.jpg",
        "isAvailable": true
    },
    {
        id: 7,
        "name": "Innova",
        "brand": "Toyota",
        "model": "SUV",
        "fuel": "Diesel",
        "mileage": 16,
        "wheels": 4,
        "seater": 5,
        "price": 2500,
        "img": "https://4.imimg.com/data4/SN/PL/MY-10330151/toyota-innova-with-a-c-5-1-500x500.jpg",
        "isAvailable": true
    },
    {
        id: 8,
        "name": "Duster",
        "brand": "Renault",
        "model": "SUV",
        "fuel": "Petrol",
        "wheels": 4,
        "mileage": 12,
        "seater": 5,
        "price": 3000,
        "img": "https://images.jdmagicbox.com/quickquotes/images_main/renault_duster_85ps_diesel_rxe_pearl_supreme_white_82809470_0.jpg",
        "isAvailable": true
    }
]

export default sampledata;